### ISSUE TITLE
Bölge paylaşma ve tarama

### ISSUE THREAD

**Issue by onurcanari** [onurcanari/webots_bitirme#1]
Her robotun receiver ve emitteri olacak. 
Receiverın mesafesi varsa o verilir: Yoksa oraya bir robotların birbirine yakın olup olmadığına dair geliştirme yapılacak. true false döndüren bir fonk.
Hepsi kapsama alanında olmalı bu sayede hiçbir haritada aynı yer taranmaması sağlanır.

**Comment by murselibol** [comment]
2.Madde için; emiter'a mesafe verebiliyoruz anladığım kadarıyla.
https://www.cyberbotics.com/doc/reference/emitter?tab-language=c++#wb_emitter_set_channel
